ALTER TABLE manufacturers
ADD COLUMN manufacturer_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE generics
ADD COLUMN generic_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE units
ADD COLUMN unit_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE units
MODIFY status ENUM('Active','Inactive') DEFAULT 'Active';

GO

ALTER TABLE racks
ADD COLUMN status ENUM('Active','Inactive') DEFAULT 'Active' AFTER description,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE warehouses
ADD COLUMN warehouse_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN city VARCHAR(100) AFTER address,
ADD COLUMN state VARCHAR(100) AFTER city,
ADD COLUMN pincode VARCHAR(10) AFTER state,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;
GO

ALTER TABLE hsn_codes
ADD COLUMN status ENUM('Active','Inactive') DEFAULT 'Active' AFTER gst_rate,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

ALTER TABLE hsn_codes
ADD CONSTRAINT uk_hsn_code UNIQUE (hsn_code);

GO

ALTER TABLE gst_rates
ADD COLUMN gst_percentage DECIMAL(5,2) AFTER gst_name,
ADD COLUMN status ENUM('Active','Inactive') DEFAULT 'Active' AFTER igst,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE tax_groups
ADD COLUMN tax_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN gst_percentage DECIMAL(5,2) AFTER igst,
ADD COLUMN status ENUM('Active','Inactive') DEFAULT 'Active' AFTER gst_percentage,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;
GO

ALTER TABLE suppliers
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE customers
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO

ALTER TABLE doctors
ADD COLUMN doctor_code VARCHAR(20) UNIQUE AFTER id,
ADD COLUMN email VARCHAR(100) AFTER mobile,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;

GO